import Express from "../public/logos/express-logo.png";
import Gmail from "../public/logos/gmail-logo.png";
import LinkedIn from "../public/logos/linkedin-logo.png";
import MongoDb from "../public/logos/mongodb-logo.png";
import Next from "../public/logos/next-logo.png";
import Node from "../public/logos/node-logo.png";
import React from "../public/logos/react-logo.png";
import Scss from "../public/logos/scss-logo.png";
import Socket from "../public/logos/socket.io-logo.png";
import Tailwind from "../public/logos/tailwind-logo.png";
import Github from "../public/logos/github-logo.svg";
import Git from "../public/logos/git-logo.svg";
import Vercel from "../public/logos/vercel-logo.svg";

export const expressLogo = Express;
export const gmailLogo = Gmail;
export const linkedinLogo = LinkedIn;
export const mongodbLogo = MongoDb;
export const nextLogo = Next;
export const nodeLogo = Node;
export const reactLogo = React;
export const scssLogo = Scss;
export const socketIoLogo = Socket;
export const tailwindLogo = Tailwind;
export const githubLogo = Github;
export const gitLogo = Git;
export const vercelLogo = Vercel;
