import Express from "../public/logos/express-logo.png";
import Gmail from "../public/logos/gmail-logo.png";
import LinkedIn from "../public/logos/linkedin-logo.png";
import MongoDb from "../public/logos/mongodb-logo.png";
import Next from "../public/logos/next-logo.png";
import Node from "../public/logos/node-logo.png";
import React from "../public/logos/react-logo.png";
import Scss from "../public/logos/scss-logo.png";
import Socket from "../public/logos/socket.io-logo.png";
import Tailwind from "../public/logos/tailwind-logo.png";
import Github from "../public/logos/github-logo.svg";
import Git from "../public/logos/git-logo.svg";
import Vercel from "../public/logos/vercel-logo.svg";

import AxiosStack from "../public/logos/stack-logos/axios.logo.png";
import CssStack from "../public/logos/stack-logos/css-logo.png";
import ExpressStack from "../public/logos/stack-logos/express-logo.png";
import GitStack from "../public/logos/stack-logos/git-logo.png";
import GithubStack from "../public/logos/stack-logos/github-logo.png";
import HerokuStack from "../public/logos/stack-logos/heroku-logo.png";
import HtmlStack from "../public/logos/stack-logos/html-logo.png";
import JsStack from "../public/logos/stack-logos/js-logo.png";
import MongodbStack from "../public/logos/stack-logos/mongodb-logo.png";
import MongooseStack from "../public/logos/stack-logos/mongoose.png";
import NextStack from "../public/logos/stack-logos/next-logo.png";
import NodeStack from "../public/logos/stack-logos/node-logo.png";
import PrismaStack from "../public/logos/stack-logos/prisma-logo.png";
import ReactStack from "../public/logos/stack-logos/react-logo.png";
import ReduxStack from "../public/logos/stack-logos/redux-logo.png";
import ScssStack from "../public/logos/stack-logos/redux-logo.png";
import SocketIoStack from "../public/logos/stack-logos/socket.io-logo.png";
import TailwindStack from "../public/logos/stack-logos/tailwind-logo.png";
import VercelStack from "../public/logos/stack-logos/vercel-logo.png";

export const expressLogo = Express;
export const gmailLogo = Gmail;
export const linkedinLogo = LinkedIn;
export const mongodbLogo = MongoDb;
export const nextLogo = Next;
export const nodeLogo = Node;
export const reactLogo = React;
export const scssLogo = Scss;
export const socketIoLogo = Socket;
export const tailwindLogo = Tailwind;
export const githubLogo = Github;
export const gitLogo = Git;
export const vercelLogo = Vercel;

export const axiosStackLogo = AxiosStack;
export const cssStackLogo = CssStack;
export const expresStackLogo = ExpressStack;
export const gitStackLogo = GitStack;
export const githubStackLogo = GithubStack;
export const herokuStackLogo = HerokuStack;
export const htmlStackLogo = HtmlStack;
export const jsStackLogo = JsStack;
export const mongodbStackLogo = MongodbStack;
export const mongooseStackLogo = MongooseStack;
export const nextStackLogo = NextStack;
export const nodeStackLogo = NodeStack;
export const prismaStackLogo = PrismaStack;
export const reactStackLogo = ReactStack;
export const reduxStackLogo = ReduxStack;
export const scssStackLogo = ScssStack;
export const socketIOStackLogo = SocketIoStack;
export const tailwindStackLogo = TailwindStack;
export const vercelStackLogo = VercelStack;
